#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -std=c++11 -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\basedatos2.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\basedatos2.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\tablavista.o $(OBJDIR_DEBUG)\\tablaControl.o $(OBJDIR_DEBUG)\\tabla.o $(OBJDIR_DEBUG)\\indice.o $(OBJDIR_DEBUG)\\campo.o $(OBJDIR_DEBUG)\\basedatos.o $(OBJDIR_DEBUG)\\baseDatosVista.o $(OBJDIR_DEBUG)\\baseDatosControl.o $(OBJDIR_DEBUG)\\lista.o $(OBJDIR_DEBUG)\\main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\tablavista.o $(OBJDIR_RELEASE)\\tablaControl.o $(OBJDIR_RELEASE)\\tabla.o $(OBJDIR_RELEASE)\\indice.o $(OBJDIR_RELEASE)\\campo.o $(OBJDIR_RELEASE)\\basedatos.o $(OBJDIR_RELEASE)\\baseDatosVista.o $(OBJDIR_RELEASE)\\baseDatosControl.o $(OBJDIR_RELEASE)\\lista.o $(OBJDIR_RELEASE)\\main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\tablavista.o: tablavista.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tablavista.cpp -o $(OBJDIR_DEBUG)\\tablavista.o

$(OBJDIR_DEBUG)\\tablaControl.o: tablaControl.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tablaControl.cpp -o $(OBJDIR_DEBUG)\\tablaControl.o

$(OBJDIR_DEBUG)\\tabla.o: tabla.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tabla.cpp -o $(OBJDIR_DEBUG)\\tabla.o

$(OBJDIR_DEBUG)\\indice.o: indice.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c indice.cpp -o $(OBJDIR_DEBUG)\\indice.o

$(OBJDIR_DEBUG)\\campo.o: campo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c campo.cpp -o $(OBJDIR_DEBUG)\\campo.o

$(OBJDIR_DEBUG)\\basedatos.o: basedatos.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c basedatos.cpp -o $(OBJDIR_DEBUG)\\basedatos.o

$(OBJDIR_DEBUG)\\baseDatosVista.o: baseDatosVista.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c baseDatosVista.cpp -o $(OBJDIR_DEBUG)\\baseDatosVista.o

$(OBJDIR_DEBUG)\\baseDatosControl.o: baseDatosControl.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c baseDatosControl.cpp -o $(OBJDIR_DEBUG)\\baseDatosControl.o

$(OBJDIR_DEBUG)\\lista.o: lista.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c lista.cpp -o $(OBJDIR_DEBUG)\\lista.o

$(OBJDIR_DEBUG)\\main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)\\main.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\tablavista.o: tablavista.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tablavista.cpp -o $(OBJDIR_RELEASE)\\tablavista.o

$(OBJDIR_RELEASE)\\tablaControl.o: tablaControl.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tablaControl.cpp -o $(OBJDIR_RELEASE)\\tablaControl.o

$(OBJDIR_RELEASE)\\tabla.o: tabla.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tabla.cpp -o $(OBJDIR_RELEASE)\\tabla.o

$(OBJDIR_RELEASE)\\indice.o: indice.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c indice.cpp -o $(OBJDIR_RELEASE)\\indice.o

$(OBJDIR_RELEASE)\\campo.o: campo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c campo.cpp -o $(OBJDIR_RELEASE)\\campo.o

$(OBJDIR_RELEASE)\\basedatos.o: basedatos.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c basedatos.cpp -o $(OBJDIR_RELEASE)\\basedatos.o

$(OBJDIR_RELEASE)\\baseDatosVista.o: baseDatosVista.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c baseDatosVista.cpp -o $(OBJDIR_RELEASE)\\baseDatosVista.o

$(OBJDIR_RELEASE)\\baseDatosControl.o: baseDatosControl.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c baseDatosControl.cpp -o $(OBJDIR_RELEASE)\\baseDatosControl.o

$(OBJDIR_RELEASE)\\lista.o: lista.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c lista.cpp -o $(OBJDIR_RELEASE)\\lista.o

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

